import { build as viteBuild } from "vite";
import { mkdir, writeFile } from "fs/promises";
import { join } from "path";

async function buildForVercel() {
  console.log("Building client for Vercel deployment...");
  
  // Create client/dist directory if it doesn't exist
  await mkdir("client/dist", { recursive: true });
  
  // Build the client
  await viteBuild({
    build: {
      outDir: "client/dist",
      emptyOutDir: true
    }
  });
  
  // The index.html is generated by Vite, so we don't need to create it manually.
  
  console.log("✅ Client built successfully for Vercel");
}

buildForVercel().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});